package Exception;

public class NestedTry {
	public static void main(String[] args) {
		try {
			p1.move();	
		}
		catch(Throwable e)
		{
			System.out.println(e);
		}
		
		
	}

}


